#!/bin/bash


#hacer databases de los reads
mkdir reads 
for file in `ls *.txt`; do awk '{print$1}' $file > reads/$file;done
cp /home/minijordi/Feina/CostaRica/prova/FilterFasta.class reads
cp /home/minijordi/Feina/CostaRica/prova/340mil_uaccno reads
cd reads
mkdir blast
for file in `ls *.txt`; do java FilterFasta 340mil_uaccno % $file > blast/$file;done
cd blast
for file in `ls *.txt`; do formatdb -i $file -p F -n $file.database;done

cp /home/minijordi/Feina/CostaRica/prova/gi2prot2.pl gi2prot2.pl
cp /home/minijordi/Feina/CostaRica/prova/script_tblastn.pl script_tblastn.pl
cp /home/minijordi/Feina/CostaRica/prova/script_tblastn.pl xml.pl
mkdir ../../tblastn_results


#introducir proteina referencia
./gi2prot2.pl

#tblastn
./script_tblastn.pl

cd ../..



